### ISSUE TITLE
Criar role para hardening do linux

### ISSUE THREAD

**Issue by gomex** [mentoriaiac/iac-role-seguranca#1]
Foco no Ubuntu 20.04, mas seria legal opções para aceitar outras versões e até mesmo debian.

**Comment by DiogoMajela** [comment]
@gomex, para o hardening da vm o projeto está utilizando alguma documentação? Caso não, teria alguma sugestão?

**Comment by gomex** [comment]
@DiogoMajela estamos aplicando esse baseline: https://dev-sec.io/baselines/linux/

**Comment by gomex** [comment]
Usaremos a role pronta mesmo.
